- name: Install MongoDB
  host: all
  become: yes
  vars:
    component: mongodb
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ component }}"

    - name: Add MongoDB repository
      ansible.builtin.copy:
        src: repo-files/mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      ansible.builtin.dnf:
        name:
          - mongodb-org
          - base-completion
        state: present

    - name: Long form task does not
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start MongoDB service
      ansible.builtin.systemd_service:
        name: mongod
        state: restarted
        enabled: true

