- name: Install Redis
  hosts: all
  become: yes
  vars:
    component: redis
  tasks:
    - name: Import Task
      ansible.builtin.import_tasks: common.yml

    - name: Install Redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Modify Redis configuration
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: '^bind\s+127\.0\.0\.1', replace: 'bind 0.0.0.0' }
        - { regexp: '^protected-mode\s+yes', replace: 'protected-mode no' }

    - name: Start Redis service
      ansible.builtin.systemd_service:
        name: redis
        state: restarted
        enabled: true
