- name: Disable default Nginx module
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx:1.24 20 module
  ansible.builtin.shell: dnf module enable nginx:1.24  -y

- name: Install Nginx:1.24
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Removing default Nginx content.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
  no_log: true

- name: Creating default Nginx content.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading the frontend web layer code.
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Configuring Nginx Configuration.
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restarting and enabling the Nginx service.
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true
  no_log: true