- name: Install RabbitMQ
  hosts: all
  become: yes
  vars:
    component: mysql
  tasks:
    - name: Import Task
      ansible.builtin.import_tasks: common.yml

    - name: Add RabbitMQ repository
      ansible.builtin.copy:
        src: repo-files/rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install RabbitMQ
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ service
      ansible.builtin.systemd:
        name: rabbitmq-server
        enabled: yes
        state: restarted

    - name: Add RabbitMQ user and set permissions.
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: "{{ pass }}"
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present