- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: MySQL root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"