- name: Roboshop Setup
  hosts: all
  become: yes
  vars:
    component: catalogue
    schema: mongodb
  tasks:
    - name: Pre-requisite Task
      ansible.builtin.import_tasks: common.yml

    - name: Import Role to setup {{component}}
      ansible.builtin.import_role:
        name: common
        tasks_from: nodejs_setup.yml