- name: Create application user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: yes
    create_home: no
    comment: "Roboshop Application User"

- name: Removing old application directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /app
    remote_src: yes