- name: Set a hostname - {{ component }}
  ansible.builtin.hostname:
    name: "{{ component }}"

- name: Install Pre-Requisite Package
  ansible.builtin.dnf:
    name: bash-completion
    state: present