- name: Installing MySQL.
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Loading the schema into MySQL.
  ansible.builtin.shell: mysql -h mysql-dev.learntechnology.cloud -uroot -p{{mysql_root_password}} < /app/schema/{{component}}.sql