- name: Installing MySQL.
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Loading all schema files into MySQL.
  ansible.builtin.shell: |
    for file in /app/db/schema.sql /app/db/app-user.sql /app/db/master-data.sql; do
      mysql -h mysql.learntechnology.space -uroot -p{{ mysql_root_password }} < "$file"
    done
  args:
    executable: /bin/bash
